version: '3'

services:
  license-server:
    build:
      context: ./license_portal
    links:
      - mariadb
    volumes:
      - ./license_portal:/app
    command: >
        bash -c "python manage.py migrate
        && python manage.py runserver 0.0.0.0:8080"
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'licences'
      MYSQL_DATABASE: 'licenses'
      MYSQL_USER: 'licenses'
      MYSQL_PASSWORD: 'licenses'
    volumes:
      - mariadb_data:/var/lib/mysql
    
volumes:
  mariadb_data:
