# Generated by Django 4.2.5 on 2023-10-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20220520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Production'), (1, 'Evaluation')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'JavaScript SDK'), (1, 'IOS SDK'), (2, 'Android SDK')]),
        ),
    ]
